admin:
  # For GRPC endpoints you might want to use dns:///flyte.myexample.com
  endpoint: dns:///playground.canary.unionai.cloud
  clientId: canary-zeryx-ci-operator
  clientSecretLocation: /var/secret
  insecure: false
  authType: ClientSecret
logger:
  show-source: true
  level: 0
union:
  connection:
    host: dns:///playground.canary.unionai.cloud
    insecure: false
  auth:
    clientId: canary-zeryx-ci-operator
    clientSecretLocation: /var/secret
    type: ClientSecret